"""Adding name column

Revision ID: 0b2a81701d30
Revises: 
Create Date: 2018-03-13 16:30:18.937608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2a81701d30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tips', sa.Column('name_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tips', 'name', ['name_id'], ['ID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tips', type_='foreignkey')
    op.drop_column('tips', 'name_id')
    # ### end Alembic commands ###
